[book]
authors = ["{{authors}}"]
language = "en"
multilingual = false
src = "docs"
title = "{{project-name}}"

[rust]
edition = "2021"

[build]
build-dir = "target/book"

[output.html]
edit-url-template = "https://github.com/{{github_username}/{{project-name}}/edit/trunk/{path}"
git-repository-url = "https://github.com/{{github_username}}/{{project-name}}"
preferred-dark-theme = "ayu"
smart-punctuation = true
